// Seed data untuk Dashboard Monitoring Dampak Bencana Sumatera
// Data dengan struktur baru: biaya per jenis infrastruktur

const seedData = [
    // ===== PROVINSI ACEH =====
    {
        id: "aceh_1",
        provinsi: "Aceh",
        kabupaten: "Kab. Pidie",
        tambakRusak: 718.00,
        biayaTambak: 71800000000,
        kolamRusak: 0,
        biayaKolam: 0,
        kjaRusak: 0,
        biayaKja: 0,
        saluran: 95000.00,
        biayaSaluran: 9500000000,
        pintuAir: 200,
        biayaPintuAir: 1000000000,
        jalanProduksi: 4000,
        biayaJalan: 12000000000,
        rehabBBI: 360,
        biayaBBI: 1800000000,
        createdAt: new Date().toISOString()
    },
    {
        id: "aceh_2",
        provinsi: "Aceh",
        kabupaten: "Kab. Pidie Jaya",
        tambakRusak: 703.00,
        biayaTambak: 70300000000,
        kolamRusak: 0,
        biayaKolam: 0,
        kjaRusak: 0,
        biayaKja: 0,
        saluran: 100000.00,
        biayaSaluran: 10000000000,
        pintuAir: 800,
        biayaPintuAir: 4000000000,
        jalanProduksi: 8000,
        biayaJalan: 24000000000,
        rehabBBI: 0,
        biayaBBI: 0,
        createdAt: new Date().toISOString()
    },
    {
        id: "aceh_3",
        provinsi: "Aceh",
        kabupaten: "Kab. Bireun",
        tambakRusak: 1978.60,
        biayaTambak: 197860000000,
        kolamRusak: 3.00,
        biayaKolam: 150000000,
        kjaRusak: 0,
        biayaKja: 0,
        saluran: 750000.00,
        biayaSaluran: 75000000000,
        pintuAir: 2200,
        biayaPintuAir: 11000000000,
        jalanProduksi: 4000,
        biayaJalan: 12000000000,
        rehabBBI: 25,
        biayaBBI: 125000000,
        createdAt: new Date().toISOString()
    },
    {
        id: "aceh_4",
        provinsi: "Aceh",
        kabupaten: "Kab. Aceh Utara",
        tambakRusak: 4269.00,
        biayaTambak: 426900000000,
        kolamRusak: 1.10,
        biayaKolam: 55000000,
        kjaRusak: 0,
        biayaKja: 0,
        saluran: 1330000.00,
        biayaSaluran: 133000000000,
        pintuAir: 2800,
        biayaPintuAir: 14000000000,
        jalanProduksi: 0,
        biayaJalan: 0,
        rehabBBI: 446,
        biayaBBI: 2230000000,
        createdAt: new Date().toISOString()
    },
    {
        id: "aceh_5",
        provinsi: "Aceh",
        kabupaten: "Kab. Aceh Timur",
        tambakRusak: 7124.00,
        biayaTambak: 712400000000,
        kolamRusak: 32.00,
        biayaKolam: 1600000000,
        kjaRusak: 0,
        biayaKja: 0,
        saluran: 250000.00,
        biayaSaluran: 25000000000,
        pintuAir: 3200,
        biayaPintuAir: 16000000000,
        jalanProduksi: 0,
        biayaJalan: 0,
        rehabBBI: 0,
        biayaBBI: 0,
        createdAt: new Date().toISOString()
    },
    {
        id: "aceh_6",
        provinsi: "Aceh",
        kabupaten: "Kab. Aceh Tamiang",
        tambakRusak: 200.00,
        biayaTambak: 20000000000,
        kolamRusak: 0,
        biayaKolam: 0,
        kjaRusak: 0,
        biayaKja: 0,
        saluran: 25000.00,
        biayaSaluran: 2500000000,
        pintuAir: 384,
        biayaPintuAir: 1920000000,
        jalanProduksi: 0,
        biayaJalan: 0,
        rehabBBI: 0,
        biayaBBI: 0,
        createdAt: new Date().toISOString()
    },
    {
        id: "aceh_7",
        provinsi: "Aceh",
        kabupaten: "Kab. Aceh Tengah",
        tambakRusak: 0,
        biayaTambak: 0,
        kolamRusak: 60.00,
        biayaKolam: 3000000000,
        kjaRusak: 140,
        biayaKja: 7875000000,
        saluran: 0,
        biayaSaluran: 0,
        pintuAir: 0,
        biayaPintuAir: 0,
        jalanProduksi: 0,
        biayaJalan: 0,
        rehabBBI: 130,
        biayaBBI: 650000000,
        createdAt: new Date().toISOString()
    },
    {
        id: "aceh_8",
        provinsi: "Aceh",
        kabupaten: "Kab. Aceh Selatan",
        tambakRusak: 0,
        biayaTambak: 0,
        kolamRusak: 13.35,
        biayaKolam: 667500000,
        kjaRusak: 0,
        biayaKja: 0,
        saluran: 22500.00,
        biayaSaluran: 2250000000,
        pintuAir: 0,
        biayaPintuAir: 0,
        jalanProduksi: 560,
        biayaJalan: 1680000000,
        rehabBBI: 0,
        biayaBBI: 0,
        createdAt: new Date().toISOString()
    },
    {
        id: "aceh_9",
        provinsi: "Aceh",
        kabupaten: "Kab. Nagan Raya",
        tambakRusak: 0,
        biayaTambak: 0,
        kolamRusak: 2.84,
        biayaKolam: 142000000,
        kjaRusak: 0,
        biayaKja: 0,
        saluran: 0,
        biayaSaluran: 0,
        pintuAir: 0,
        biayaPintuAir: 0,
        jalanProduksi: 0,
        biayaJalan: 0,
        rehabBBI: 0,
        biayaBBI: 0,
        createdAt: new Date().toISOString()
    },
    {
        id: "aceh_10",
        provinsi: "Aceh",
        kabupaten: "Kab. Aceh Barat",
        tambakRusak: 0,
        biayaTambak: 0,
        kolamRusak: 5.41,
        biayaKolam: 270500000,
        kjaRusak: 0,
        biayaKja: 0,
        saluran: 0,
        biayaSaluran: 0,
        pintuAir: 0,
        biayaPintuAir: 0,
        jalanProduksi: 0,
        biayaJalan: 0,
        rehabBBI: 0,
        biayaBBI: 0,
        createdAt: new Date().toISOString()
    },
    {
        id: "aceh_11",
        provinsi: "Aceh",
        kabupaten: "Kab. Bener Meriah",
        tambakRusak: 0,
        biayaTambak: 0,
        kolamRusak: 15.00,
        biayaKolam: 750000000,
        kjaRusak: 0,
        biayaKja: 0,
        saluran: 0,
        biayaSaluran: 0,
        pintuAir: 0,
        biayaPintuAir: 0,
        jalanProduksi: 0,
        biayaJalan: 0,
        rehabBBI: 0,
        biayaBBI: 0,
        createdAt: new Date().toISOString()
    },
    {
        id: "aceh_12",
        provinsi: "Aceh",
        kabupaten: "Kab. Gayo Luwes",
        tambakRusak: 0,
        biayaTambak: 0,
        kolamRusak: 17.47,
        biayaKolam: 873500000,
        kjaRusak: 0,
        biayaKja: 0,
        saluran: 0,
        biayaSaluran: 0,
        pintuAir: 0,
        biayaPintuAir: 0,
        jalanProduksi: 0,
        biayaJalan: 0,
        rehabBBI: 96,
        biayaBBI: 480000000,
        createdAt: new Date().toISOString()
    },
    {
        id: "aceh_13",
        provinsi: "Aceh",
        kabupaten: "Kab. Aceh Tenggara",
        tambakRusak: 0,
        biayaTambak: 0,
        kolamRusak: 10.32,
        biayaKolam: 516000000,
        kjaRusak: 0,
        biayaKja: 0,
        saluran: 0,
        biayaSaluran: 0,
        pintuAir: 0,
        biayaPintuAir: 0,
        jalanProduksi: 0,
        biayaJalan: 0,
        rehabBBI: 0,
        biayaBBI: 0,
        createdAt: new Date().toISOString()
    },
    {
        id: "aceh_14",
        provinsi: "Aceh",
        kabupaten: "Kab. Aceh Singkil",
        tambakRusak: 0,
        biayaTambak: 0,
        kolamRusak: 1.42,
        biayaKolam: 71000000,
        kjaRusak: 20,
        biayaKja: 1125000000,
        saluran: 0,
        biayaSaluran: 0,
        pintuAir: 0,
        biayaPintuAir: 0,
        jalanProduksi: 0,
        biayaJalan: 0,
        rehabBBI: 66,
        biayaBBI: 332400000,
        createdAt: new Date().toISOString()
    },
    {
        id: "aceh_15",
        provinsi: "Aceh",
        kabupaten: "Kota Lhoukseumawe",
        tambakRusak: 204.00,
        biayaTambak: 20400000000,
        kolamRusak: 0.31,
        biayaKolam: 15500000,
        kjaRusak: 0,
        biayaKja: 0,
        saluran: 35000.00,
        biayaSaluran: 3500000000,
        pintuAir: 120,
        biayaPintuAir: 600000000,
        jalanProduksi: 7520,
        biayaJalan: 22560000000,
        rehabBBI: 0,
        biayaBBI: 0,
        createdAt: new Date().toISOString()
    },
    {
        id: "aceh_16",
        provinsi: "Aceh",
        kabupaten: "Kota Langsa",
        tambakRusak: 700.00,
        biayaTambak: 70000000000,
        kolamRusak: 0,
        biayaKolam: 0,
        kjaRusak: 330,
        biayaKja: 18562500000,
        saluran: 5000.00,
        biayaSaluran: 500000000,
        pintuAir: 220,
        biayaPintuAir: 1100000000,
        jalanProduksi: 0,
        biayaJalan: 0,
        rehabBBI: 0,
        biayaBBI: 0,
        createdAt: new Date().toISOString()
    },
    
    // ===== PROVINSI SUMATERA UTARA =====
    {
        id: "sumut_1",
        provinsi: "Sumatera Utara",
        kabupaten: "Kab. Langkat",
        tambakRusak: 82.39,
        biayaTambak: 8239000000,
        kolamRusak: 8.67,
        biayaKolam: 433500000,
        kjaRusak: 0,
        biayaKja: 0,
        saluran: 0,
        biayaSaluran: 0,
        pintuAir: 0,
        biayaPintuAir: 0,
        jalanProduksi: 0,
        biayaJalan: 0,
        rehabBBI: 0,
        biayaBBI: 0,
        createdAt: new Date().toISOString()
    },
    {
        id: "sumut_2",
        provinsi: "Sumatera Utara",
        kabupaten: "Kab. Deli Serdang",
        tambakRusak: 236.78,
        biayaTambak: 23678000000,
        kolamRusak: 46.63,
        biayaKolam: 2331500000,
        kjaRusak: 0,
        biayaKja: 0,
        saluran: 0,
        biayaSaluran: 0,
        pintuAir: 0,
        biayaPintuAir: 0,
        jalanProduksi: 0,
        biayaJalan: 0,
        rehabBBI: 100,
        biayaBBI: 500000000,
        createdAt: new Date().toISOString()
    },
    {
        id: "sumut_3",
        provinsi: "Sumatera Utara",
        kabupaten: "Kab. Tapanuli Tengah",
        tambakRusak: 0,
        biayaTambak: 0,
        kolamRusak: 25.02,
        biayaKolam: 1251000000,
        kjaRusak: 0,
        biayaKja: 10000000,
        saluran: 100,
        biayaSaluran: 10000000,
        pintuAir: 0,
        biayaPintuAir: 0,
        jalanProduksi: 0,
        biayaJalan: 0,
        rehabBBI: 0,
        biayaBBI: 0,
        createdAt: new Date().toISOString()
    },
    {
        id: "sumut_4",
        provinsi: "Sumatera Utara",
        kabupaten: "Kab. Tapanuli Selatan",
        tambakRusak: 0,
        biayaTambak: 0,
        kolamRusak: 8.60,
        biayaKolam: 430000000,
        kjaRusak: 0,
        biayaKja: 990000000,
        saluran: 9900,
        biayaSaluran: 990000000,
        pintuAir: 0,
        biayaPintuAir: 0,
        jalanProduksi: 0,
        biayaJalan: 0,
        rehabBBI: 200,
        biayaBBI: 1000000000,
        createdAt: new Date().toISOString()
    },
    {
        id: "sumut_5",
        provinsi: "Sumatera Utara",
        kabupaten: "Kab. Tapanuli Utara",
        tambakRusak: 0,
        biayaTambak: 0,
        kolamRusak: 2.57,
        biayaKolam: 128500000,
        kjaRusak: 0,
        biayaKja: 500000000,
        saluran: 5000,
        biayaSaluran: 500000000,
        pintuAir: 0,
        biayaPintuAir: 0,
        jalanProduksi: 0,
        biayaJalan: 0,
        rehabBBI: 100,
        biayaBBI: 500000000,
        createdAt: new Date().toISOString()
    },
    {
        id: "sumut_6",
        provinsi: "Sumatera Utara",
        kabupaten: "Kota Sibolga",
        tambakRusak: 0,
        biayaTambak: 0,
        kolamRusak: 0.11,
        biayaKolam: 5500000,
        kjaRusak: 0,
        biayaKja: 0,
        saluran: 0,
        biayaSaluran: 0,
        pintuAir: 0,
        biayaPintuAir: 0,
        jalanProduksi: 0,
        biayaJalan: 0,
        rehabBBI: 0,
        biayaBBI: 0,
        createdAt: new Date().toISOString()
    },
    {
        id: "sumut_7",
        provinsi: "Sumatera Utara",
        kabupaten: "Kota Padang Sidempuan",
        tambakRusak: 0,
        biayaTambak: 0,
        kolamRusak: 2.15,
        biayaKolam: 107500000,
        kjaRusak: 0,
        biayaKja: 0,
        saluran: 0,
        biayaSaluran: 0,
        pintuAir: 0,
        biayaPintuAir: 0,
        jalanProduksi: 0,
        biayaJalan: 0,
        rehabBBI: 300,
        biayaBBI: 1500000000,
        createdAt: new Date().toISOString()
    },
    {
        id: "sumut_8",
        provinsi: "Sumatera Utara",
        kabupaten: "Kota Medan",
        tambakRusak: 25.32,
        biayaTambak: 2532000000,
        kolamRusak: 66.01,
        biayaKolam: 3300500000,
        kjaRusak: 0,
        biayaKja: 0,
        saluran: 0,
        biayaSaluran: 0,
        pintuAir: 0,
        biayaPintuAir: 0,
        jalanProduksi: 0,
        biayaJalan: 0,
        rehabBBI: 0,
        biayaBBI: 0,
        createdAt: new Date().toISOString()
    },
    {
        id: "sumut_9",
        provinsi: "Sumatera Utara",
        kabupaten: "Kab. Asahan",
        tambakRusak: 0,
        biayaTambak: 0,
        kolamRusak: 1.22,
        biayaKolam: 61000000,
        kjaRusak: 0,
        biayaKja: 0,
        saluran: 0,
        biayaSaluran: 0,
        pintuAir: 0,
        biayaPintuAir: 0,
        jalanProduksi: 0,
        biayaJalan: 0,
        rehabBBI: 0,
        biayaBBI: 0,
        createdAt: new Date().toISOString()
    },
    {
        id: "sumut_10",
        provinsi: "Sumatera Utara",
        kabupaten: "Kab. Batubara",
        tambakRusak: 31.00,
        biayaTambak: 3100000000,
        kolamRusak: 24.20,
        biayaKolam: 1210000000,
        kjaRusak: 0,
        biayaKja: 0,
        saluran: 0,
        biayaSaluran: 0,
        pintuAir: 0,
        biayaPintuAir: 0,
        jalanProduksi: 0,
        biayaJalan: 0,
        rehabBBI: 0,
        biayaBBI: 0,
        createdAt: new Date().toISOString()
    },
    {
        id: "sumut_11",
        provinsi: "Sumatera Utara",
        kabupaten: "Kab. Humbang Hasundutan",
        tambakRusak: 0,
        biayaTambak: 0,
        kolamRusak: 1.45,
        biayaKolam: 72500000,
        kjaRusak: 0,
        biayaKja: 0,
        saluran: 0,
        biayaSaluran: 0,
        pintuAir: 0,
        biayaPintuAir: 0,
        jalanProduksi: 0,
        biayaJalan: 0,
        rehabBBI: 0,
        biayaBBI: 0,
        createdAt: new Date().toISOString()
    },
    
    // ===== PROVINSI SUMATERA BARAT =====
    {
        id: "sumbar_1",
        provinsi: "Sumatera Barat",
        kabupaten: "Kab. Pasaman",
        tambakRusak: 0,
        biayaTambak: 0,
        kolamRusak: 43.50,
        biayaKolam: 2175000000,
        kjaRusak: 0,
        biayaKja: 0,
        saluran: 500,
        biayaSaluran: 50000000,
        pintuAir: 0,
        biayaPintuAir: 0,
        jalanProduksi: 800,
        biayaJalan: 2400000000,
        rehabBBI: 0,
        biayaBBI: 0,
        createdAt: new Date().toISOString()
    },
    {
        id: "sumbar_2",
        provinsi: "Sumatera Barat",
        kabupaten: "Kab. Solok",
        tambakRusak: 0,
        biayaTambak: 0,
        kolamRusak: 8.00,
        biayaKolam: 400000000,
        kjaRusak: 0,
        biayaKja: 0,
        saluran: 0,
        biayaSaluran: 0,
        pintuAir: 15,
        biayaPintuAir: 75000000,
        jalanProduksi: 0,
        biayaJalan: 0,
        rehabBBI: 0,
        biayaBBI: 0,
        createdAt: new Date().toISOString()
    },
    {
        id: "sumbar_3",
        provinsi: "Sumatera Barat",
        kabupaten: "Kab. Pesisir Selatan",
        tambakRusak: 0,
        biayaTambak: 0,
        kolamRusak: 1.00,
        biayaKolam: 50000000,
        kjaRusak: 0,
        biayaKja: 0,
        saluran: 0,
        biayaSaluran: 0,
        pintuAir: 0,
        biayaPintuAir: 0,
        jalanProduksi: 0,
        biayaJalan: 0,
        rehabBBI: 108,
        biayaBBI: 540000000,
        createdAt: new Date().toISOString()
    },
    {
        id: "sumbar_4",
        provinsi: "Sumatera Barat",
        kabupaten: "Kab. Lima Puluh Kota",
        tambakRusak: 0,
        biayaTambak: 0,
        kolamRusak: 0.60,
        biayaKolam: 30000000,
        kjaRusak: 0,
        biayaKja: 0,
        saluran: 0,
        biayaSaluran: 0,
        pintuAir: 0,
        biayaPintuAir: 0,
        jalanProduksi: 0,
        biayaJalan: 0,
        rehabBBI: 0,
        biayaBBI: 0,
        createdAt: new Date().toISOString()
    },
    {
        id: "sumbar_5",
        provinsi: "Sumatera Barat",
        kabupaten: "Kab. Agam",
        tambakRusak: 0,
        biayaTambak: 0,
        kolamRusak: 30.70,
        biayaKolam: 1535000000,
        kjaRusak: 0,
        biayaKja: 0,
        saluran: 1500,
        biayaSaluran: 150000000,
        pintuAir: 0,
        biayaPintuAir: 0,
        jalanProduksi: 0,
        biayaJalan: 0,
        rehabBBI: 0,
        biayaBBI: 0,
        createdAt: new Date().toISOString()
    },
    {
        id: "sumbar_6",
        provinsi: "Sumatera Barat",
        kabupaten: "Kab. Padang Pariaman",
        tambakRusak: 0,
        biayaTambak: 0,
        kolamRusak: 6.90,
        biayaKolam: 345000000,
        kjaRusak: 60,
        biayaKja: 3450000000,
        saluran: 0,
        biayaSaluran: 0,
        pintuAir: 0,
        biayaPintuAir: 0,
        jalanProduksi: 0,
        biayaJalan: 0,
        rehabBBI: 3000,
        biayaBBI: 15000000000,
        createdAt: new Date().toISOString()
    },
    {
        id: "sumbar_7",
        provinsi: "Sumatera Barat",
        kabupaten: "Kab. Tanah Datar",
        tambakRusak: 0,
        biayaTambak: 0,
        kolamRusak: 3.90,
        biayaKolam: 195000000,
        kjaRusak: 0,
        biayaKja: 0,
        saluran: 4580,
        biayaSaluran: 458000000,
        pintuAir: 0,
        biayaPintuAir: 0,
        jalanProduksi: 0,
        biayaJalan: 0,
        rehabBBI: 0,
        biayaBBI: 0,
        createdAt: new Date().toISOString()
    },
    {
        id: "sumbar_8",
        provinsi: "Sumatera Barat",
        kabupaten: "Kota Pariaman",
        tambakRusak: 0,
        biayaTambak: 0,
        kolamRusak: 38.40,
        biayaKolam: 1920000000,
        kjaRusak: 0,
        biayaKja: 0,
        saluran: 3800,
        biayaSaluran: 380000000,
        pintuAir: 0,
        biayaPintuAir: 0,
        jalanProduksi: 0,
        biayaJalan: 0,
        rehabBBI: 0,
        biayaBBI: 0,
        createdAt: new Date().toISOString()
    },
    {
        id: "sumbar_9",
        provinsi: "Sumatera Barat",
        kabupaten: "Kota Solok",
        tambakRusak: 0,
        biayaTambak: 0,
        kolamRusak: 30.90,
        biayaKolam: 1545000000,
        kjaRusak: 0,
        biayaKja: 0,
        saluran: 0,
        biayaSaluran: 0,
        pintuAir: 0,
        biayaPintuAir: 0,
        jalanProduksi: 0,
        biayaJalan: 0,
        rehabBBI: 250,
        biayaBBI: 1250000000,
        createdAt: new Date().toISOString()
    },
    {
        id: "sumbar_10",
        provinsi: "Sumatera Barat",
        kabupaten: "Kota Padang",
        tambakRusak: 0,
        biayaTambak: 0,
        kolamRusak: 91.00,
        biayaKolam: 4550000000,
        kjaRusak: 0,
        biayaKja: 0,
        saluran: 1200,
        biayaSaluran: 120000000,
        pintuAir: 0,
        biayaPintuAir: 0,
        jalanProduksi: 0,
        biayaJalan: 0,
        rehabBBI: 276,
        biayaBBI: 1380000000,
        createdAt: new Date().toISOString()
    },
    {
        id: "sumbar_11",
        provinsi: "Sumatera Barat",
        kabupaten: "Kab. Kep. Mentawai",
        tambakRusak: 0,
        biayaTambak: 0,
        kolamRusak: 1.00,
        biayaKolam: 50000000,
        kjaRusak: 0,
        biayaKja: 0,
        saluran: 0,
        biayaSaluran: 0,
        pintuAir: 0,
        biayaPintuAir: 0,
        jalanProduksi: 0,
        biayaJalan: 0,
        rehabBBI: 0,
        biayaBBI: 0,
        createdAt: new Date().toISOString()
    }
];

// Force load new data on initialization (always replace with new structure)
if (typeof window !== 'undefined') {
    document.addEventListener('DOMContentLoaded', function() {
        // Always force update with latest seed data
        localStorage.setItem('budidayaData', JSON.stringify(seedData));
        console.log('✅ Data berhasil dimuat! Total: ' + seedData.length + ' entri.');
        console.log('📊 Provinsi: Aceh (16), Sumatera Utara (11), Sumatera Barat (11)');
        
        if (typeof refreshAll === 'function') {
            refreshAll();
        }
    });
}

// Export for manual use
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { seedData };
}
